### ISSUE TITLE
Forcing array with null as value results in array with single null value

### ISSUE THREAD

**Issue by Svenskapojkarna** [CommunityHiQ/Frends.Community.JSON#3]
This issue is moved from https://github.com/CommunityHiQ/Frends.Community.JSON.EnforceJSONTypes

JSON such as this
`{
    "arrays": [
        {
            "array": null
        },
        {
            "array": {
                "prop": null
            }
        }
    ]
}`

end up forced as:
`{
    "arrays": [
        {
            "array": [
                null
            ]
        },
        {
            "array": [
                {
                    "prop": null
                }
            ]
        }
    ]
}`

where array has Count of 1 instead of 0.

Expected result is:
`{
    "arrays": [
        {
            "array": null
        },
        {
            "array": [
                {
                    "prop": null
                }
            ]
        }
    ]
}`

**Comment by RikuVirtanen** [comment]
Added check for null array and array that has "null" (string) value.
